### PR TITLE
Testing label permission

### PR DESCRIPTION
**Pull request by abhibhaw**

### CODE REVIEW

**Comment by CIPHERTron** [comment]
@abhibhaw 👀

**Review by CIPHERTron — APPROVED** [review]

**Comment by abhibhaw** [comment]
Hehe test successful 😄

**Comment by CIPHERTron** [comment]
Yoooooo (^ - - ^)

**Comment by CIPHERTron** [comment]
@abhibhaw this repo will be a github actions playground from now onwards XD

**Comment by abhibhaw** [comment]
🤣🤣

**Pull request closed without merging**
